services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  service1:
    build: ./service1
    ports:
      - "5001:5001"
  service4:
    build: ./service4
    ports:
      - "5004:5004"
  service7:
    build: ./service7
    ports:
      - "5007:5007"

  service01:
    build: ./service01
    ports:
      - "5011:5011"

  service8:  
    build: ./service8
    ports:
      - "5008:5008"

  service3:
    build: ./service3
    ports:
    - "5003:5003"
